steps:
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c", "docker build -t gcr.io/${PROJECT_ID}/${SERVICE_NAME} . "]
  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push gcr.io/${PROJECT_ID}/${SERVICE_NAME}"]

images:
  - "gcr.io/${PROJECT_ID}/${SERVICE_NAME}"
substitutions:
  SERVICE_NAME: "img-service"